package fpoly.edu.jewelleryStore.Entity;

import jakarta.persistence.*;
import lombok.Data;

@Data
@Entity
@Table(name="CartDetail")
public class CartDetail {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "idCartDetail")
    private Integer idCartDetail;

    @ManyToOne
    @JoinColumn(name = "idCart", referencedColumnName = "idCart")
    private Carts cart;

    @ManyToOne
    @JoinColumn(name = "idProduct", referencedColumnName = "idProduct")
    private Product product;

    @Column(name = "quantity")
    private Integer quantity;

    // Constructors, getters, and setters can be omitted as they are generated by Lombok's @Data annotation
}
