package fpoly.edu.jewelleryStore.Entity;

import jakarta.persistence.*;
import lombok.Data;

import java.sql.Date;

@Data
@Entity
@Table(name="Carts")
public class Carts {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "idCart")
    private Integer idCart;

    @ManyToOne
    @JoinColumn(name = "idUser", referencedColumnName = "idUser")
    private AppUser appUser;

    @Column(name = "dateCreate")
    private Date dateCreate;

    // Constructors, getters, and setters can be omitted as they are generated by Lombok's @Data annotation
}
