package fpoly.edu.jewelleryStore.Entity;

import jakarta.persistence.*;
import lombok.Data;

@Data
@Entity
@Table(name="Orders")
public class Orders {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "idOrder")
    private Integer idOrder;

    @ManyToOne
    @JoinColumn(name = "idUser", referencedColumnName = "idUser", nullable = false)
    private AppUser appUser;

    @Column(name = "orderDate")
    private java.sql.Date orderDate;

    @ManyToOne
    @JoinColumn(name = "idStatus", referencedColumnName = "idStatus")
    private Status status;

    @Column(name = "phoneNumber", length = 20)
    private String phoneNumber;

    @Column(name = "address", columnDefinition = "NVARCHAR(MAX)")
    private String address;

    // Constructors, getters, and setters can be omitted as they are generated by Lombok's @Data annotation
}
