package fpoly.edu.jewelleryStore.Entity;

import java.util.List;

import jakarta.persistence.*;
import lombok.Data;

@Data
@Entity
@Table(name="Orders")
public class Orders {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "idorder")
    private Integer idOrder;

    @ManyToOne
    @JoinColumn(name = "iduser", referencedColumnName = "iduser", nullable = false)
    private AppUser appUser;

    @Column(name = "orderdate")
    private java.sql.Date orderDate;

    @ManyToOne
    @JoinColumn(name = "idstatus", referencedColumnName = "idstatus")
    private Status status;

    @Column(name = "phonenumber", length = 20)
    private String phoneNumber;

    @Column(name = "address", columnDefinition = "NVARCHAR(MAX)")
    private String address;
    
   

    // Constructors, getters, and setters can be omitted as they are generated by Lombok's @Data annotation
}
