package fpoly.edu.jewelleryStore.Entity;

import jakarta.persistence.*;
import lombok.Data;

@Data
@Entity
@Table(name="Status")
public class Status {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "idStatus")
    private Integer idStatus;

    @Column(name = "name", nullable = false, length = 50)
    private String name;

    // Constructors, getters, and setters can be omitted as they are generated by Lombok's @Data annotation
}
